name: miwakpon
description: "Miwakpon - Gestionnaire d'événements synchronisé en temps réel"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Backend & Auth
  supabase_flutter: ^2.12.4

  # Navigation
  go_router: ^17.2.2

  # State Management (MVVM)
  provider: ^6.1.5

  # Typographie
  google_fonts: ^8.1.0

  # Internationalisation / Dates
  intl: ^0.20.2
# <<<<<<< HEAD
  
  # Environment variables
  flutter_dotenv: ^6.0.1
  
  # Image picker
  # image_picker: ^1.1.2
# =======
  image_picker: ^1.2.1
# >>>>>>> cd9e98ff749ceed05c4149351c66fa72091876df

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/gradient/
    - assets/images/
    - assets/.env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.jpg"
  min_sdk_android: 21
